# Generated by Django 4.2.30 on 2026-07-16

from django.db import migrations, models


def ensure_counselor_announcement_schema(apps, schema_editor):
    connection = schema_editor.connection

    def table_exists(table_name):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT 1
                FROM information_schema.TABLES
                WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s
                LIMIT 1
                """,
                [table_name],
            )
            return cursor.fetchone() is not None

    def column_exists(table_name, column_name):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT 1
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = %s
                LIMIT 1
                """,
                [table_name, column_name],
            )
            return cursor.fetchone() is not None

    with connection.cursor() as cursor:
        if not column_exists('counselor_announcement', 'allow_comments'):
            cursor.execute(
                "ALTER TABLE counselor_announcement "
                "ADD COLUMN allow_comments bool NOT NULL DEFAULT 0"
            )
        if not column_exists('counselor_announcement', 'is_important'):
            cursor.execute(
                "ALTER TABLE counselor_announcement "
                "ADD COLUMN is_important bool NOT NULL DEFAULT 0"
            )
        if not column_exists('counselor_announcement', 'published_at'):
            cursor.execute(
                "ALTER TABLE counselor_announcement "
                "ADD COLUMN published_at datetime(6) NULL"
            )
        if not column_exists('counselor_announcement', 'views_count'):
            cursor.execute(
                "ALTER TABLE counselor_announcement "
                "ADD COLUMN views_count integer UNSIGNED NOT NULL DEFAULT 0"
            )
        if not table_exists('counselor_announcement_specific_students'):
            cursor.execute(
                """
                CREATE TABLE counselor_announcement_specific_students (
                    id bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                    announcement_id bigint NOT NULL,
                    students_id bigint NOT NULL,
                    INDEX counselor_ann_student_announcement_idx (announcement_id),
                    INDEX counselor_ann_student_student_idx (students_id)
                )
                """
            )


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0016_mentor_notification_types'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_counselor_announcement_schema,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CounselorAnnouncementSpecificStudent',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'counselor_announcement_specific_students',
                        'managed': False,
                    },
                ),
                migrations.AddField(
                    model_name='counselorannouncement',
                    name='allow_comments',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='counselorannouncement',
                    name='is_important',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='counselorannouncement',
                    name='published_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='counselorannouncement',
                    name='views_count',
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AlterField(
                    model_name='courses',
                    name='course_type',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AlterField(
                    model_name='counselorannouncement',
                    name='specific_students',
                    field=models.ManyToManyField(
                        blank=True,
                        related_name='counselor_specific_announcements',
                        through='connect.CounselorAnnouncementSpecificStudent',
                        to='connect.students',
                    ),
                ),
            ],
        ),
    ]
