# Generated by Django 4.2.30 on 2026-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0017_counselorannouncementspecificstudent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
