# Generated by Django 4.2.30 on 2026-07-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0018_courses_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionnotification',
            name='notification_type',
            field=models.CharField(choices=[('session_completed', 'Session Completed'), ('doubt_raised', 'Doubt Raised'), ('doubt_resolved', 'Doubt Resolved'), ('leave_alert', 'Leave Alert'), ('assignment', 'Assignment'), ('batch_ending_soon', 'Batch Ending Soon'), ('batch_duration_exceeded', 'Batch Duration Exceeded'), ('quiz_result', 'Quiz Result'), ('leave_application', 'Leave Application'), ('announcement', 'Announcement'), ('support', 'Support')], max_length=50),
        ),
    ]
