# Generated by Django 4.2.30 on 2026-08-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0020_student_login_rating_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentloginratingevent',
            new_name='student_log_student_145bf3_idx',
            old_name='connect_stu_student_b74338_idx',
        ),
        migrations.RenameIndex(
            model_name='studentloginratingevent',
            new_name='student_log_student_ff87a6_idx',
            old_name='connect_stu_student_476495_idx',
        ),
    ]
