# Generated by Django 4.2.30 on 2026-09-01 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0026_batchtrainerassignment_batch_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztest',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_tests', to='connect.courses'),
        ),
        migrations.AddField(
            model_name='quiztest',
            name='creation_method',
            field=models.CharField(choices=[('manual', 'Create Questions Manually'), ('upload', 'Upload Question Paper')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='quiztest',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='quiztest',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiztest',
            name='question_paper',
            field=models.FileField(blank=True, null=True, upload_to='technical_tests/'),
        ),
        migrations.AddField(
            model_name='quiztest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiztest',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiztest',
            name='test_type',
            field=models.CharField(choices=[('mcq', 'MCQ Test'), ('technical', 'Technical Test')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
